name: Docker build - dev
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      -
        name: Checkout repository ( + submodules)
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: whoisdonlee/iobio_container:${{ github.ref_name }}
