name: Docker build (native)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      -
        name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          # GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          # echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Checkout repository ( + submodules)
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: whoisonlee/iobio_container:${{ env.BRANCH }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
